### ISSUE TITLE
Call to fmiTerminate

### ISSUE THREAD

**Issue by tinrabuzin** [beutlich/LastLib#2]
When a simulation crashes (due to external reasons), I get the following output:
```
[ERROR][Last] [error][FMU status:Error] fmiTerminate: Illegal call sequence.
```
I guess it's not really a big deal, but maybe you want to know about it.

**Comment by beutlich** [comment]
According to the FMI 1.0.x specification it is not allowed to call fmiTerminate after one of the previous functions calls returned fmiError or fmiFatal. This is what this message is about. Thus, it basically proves that the FMU simulation tool is not compliant with the FMI specification. Unfortunately, this even includes the [FMU/FMI Compliance Checker](https://github.com/modelica-tools/FMUComplianceChecker) itself, see https://github.com/modelica-tools/FMUComplianceChecker/issues/26. Thus, if other FMU simlation tools adopt the calling scheme from FMU/FMI Compliance Checker, the same error messages can be observed with FMUs generated by [FMU-SDK](https://github.com/qtronic/fmusdk), e.g. Last.fmu.

**Comment by beutlich** [comment]
I also improve the verbosity of that message by 3d614a2.

```
	[FMU][error][FMU status:Error] fmiTerminate: Illegal call sequence.
	[FMU][error][FMU status:Error] fmiTerminate must not be called in FMU state Error. Expected FMU state(s): Initialized.
```

**Comment by tinrabuzin** [comment]
@beutlich Is there maybe an option to disable the FMU logging the errors as well?

**Comment by beutlich** [comment]
I could change that error mesage to a debug message such that it only is logged for maximal FMU logging verbosity. Would this be of help?

**Comment by tinrabuzin** [comment]
I would appreciate it. I am sort of running simulations in the loop and some of them fail. So the output is cluttered with the error messages.

**Comment by beutlich** [comment]
OK, I disabled that single error check by d580f0b.
